#pragma once
// Lib_FField.h — Missing FField property types, linked list iterators, FieldCast.

#include <cassert>
#include <iterator>
#include "Lib_Forward.h"

// =========================================================================
// Missing FField property types (not generated by Dumper-7)
// =========================================================================

class FNumericProperty : public FProperty {};

class FInt8Property    final : public FNumericProperty {};
class FInt16Property   final : public FNumericProperty {};
class FIntProperty     final : public FNumericProperty {};
class FInt64Property   final : public FNumericProperty {};
class FUInt16Property  final : public FNumericProperty {};
class FUInt32Property  final : public FNumericProperty {};
class FUInt64Property  final : public FNumericProperty {};
class FFloatProperty   final : public FNumericProperty {};
class FDoubleProperty  final : public FNumericProperty {};

class FStrProperty     final : public FProperty {};
class FNameProperty    final : public FProperty {};
class FTextProperty    final : public FProperty {};

class FInterfaceProperty final : public FProperty
{
public:
    class UClass* InterfaceClass;
};

class FSoftObjectProperty : public FObjectPropertyBase {};
class FSoftClassProperty   final : public FSoftObjectProperty {};
class FWeakObjectProperty  final : public FObjectPropertyBase {};
class FLazyObjectProperty  final : public FObjectPropertyBase {};
class FObjectProperty      final : public FObjectPropertyBase {};

class FMulticastDelegateProperty : public FProperty
{
public:
    class UFunction* SignatureFunction;
};
class FMulticastInlineDelegateProperty final : public FMulticastDelegateProperty {};
class FMulticastSparseDelegateProperty final : public FMulticastDelegateProperty {};

// =========================================================================
// Replicated property defines
// =========================================================================
enum ELifetimeRepNotifyCondition
{
    REPNOTIFY_OnChanged = 0             ,// Only call the property's RepNotify function if it changes from the local value
    REPNOTIFY_Always = 1                ,// Always Call the property's RepNotify function when it is received from the server
};
class FLifetimeProperty
{
public:

    uint16 RepIndex;
    ELifetimeCondition Condition;
    ELifetimeRepNotifyCondition RepNotifyCondition;
    bool bIsPushBased;

    FLifetimeProperty()
        : RepIndex(0)
        , Condition(ELifetimeCondition::COND_None)
        , RepNotifyCondition(ELifetimeRepNotifyCondition::REPNOTIFY_OnChanged)
        , bIsPushBased(false)
    {
    }

    FLifetimeProperty(int32 InRepIndex)
        : RepIndex(InRepIndex)
        , Condition(ELifetimeCondition::COND_None)
        , RepNotifyCondition(ELifetimeRepNotifyCondition::REPNOTIFY_OnChanged)
        , bIsPushBased(false)
    {
        assert(InRepIndex <= 65535);
    }

    FLifetimeProperty(
        int32 InRepIndex, 
        ELifetimeCondition InCondition, 
        ELifetimeRepNotifyCondition InRepNotifyCondition = ELifetimeRepNotifyCondition::REPNOTIFY_OnChanged, 
        bool bInIsPushBased = false
    )
        : RepIndex(InRepIndex)
        , Condition(InCondition)
        , RepNotifyCondition(InRepNotifyCondition)
        , bIsPushBased(bInIsPushBased)
    {
        assert(InRepIndex <= 65535);
    }

    inline bool operator==(const FLifetimeProperty& Other) const
    {
        if (RepIndex == Other.RepIndex)
        {
            assert(Condition == Other.Condition);
            assert(RepNotifyCondition == Other.RepNotifyCondition);
            assert(bIsPushBased == Other.bIsPushBased);
            return true;
        }

        return false;
    }
};

// =========================================================================
// Linked list iterators
// =========================================================================

template<typename TNode, typename T = TNode>
struct TLinkedListIterator
{
    using iterator_category = std::forward_iterator_tag;
    using value_type = T;
    using difference_type = std::ptrdiff_t;
    using pointer = T*;
    using reference = T&;

    explicit TLinkedListIterator(TNode* start) : current_(start) {}

    pointer operator*()  const { return static_cast<pointer>(current_); }
    pointer operator->() const { return static_cast<pointer>(current_); }
    TLinkedListIterator& operator++() { current_ = current_ ? current_->Next : nullptr; return *this; }
    TLinkedListIterator  operator++(int) { auto tmp = *this; ++(*this); return tmp; }
    bool operator==(const TLinkedListIterator& o) const { return current_ == o.current_; }
    bool operator!=(const TLinkedListIterator& o) const { return current_ != o.current_; }
private:
    TNode* current_;
};

template<typename TNode, typename T = TNode>
struct TLinkedListRange
{
    explicit TLinkedListRange(TNode* start) : start_(start) {}
    TLinkedListIterator<TNode, T> begin() const { return TLinkedListIterator<TNode, T>(start_); }
    TLinkedListIterator<TNode, T> end()   const { return TLinkedListIterator<TNode, T>(nullptr); }
private:
    TNode* start_;
};

using FFieldIterator = TLinkedListIterator<FField>;
using FFieldRange = TLinkedListRange<FField>;
using UFieldIterator = TLinkedListIterator<UField>;
using UFieldRange = TLinkedListRange<UField>;

// =========================================================================
// FieldCast
// =========================================================================

namespace FieldCast
{
    template<typename T> struct TCastFlagTraits;
    template<> struct TCastFlagTraits<FField> { static constexpr EClassCastFlags Flag = EClassCastFlags::Field; };
    template<> struct TCastFlagTraits<FProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::Property; };
    template<> struct TCastFlagTraits<FNumericProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::NumericProperty; };
    template<> struct TCastFlagTraits<FByteProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::ByteProperty; };
    template<> struct TCastFlagTraits<FBoolProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::BoolProperty; };
    template<> struct TCastFlagTraits<FIntProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::IntProperty; };
    template<> struct TCastFlagTraits<FInt8Property> { static constexpr EClassCastFlags Flag = EClassCastFlags::Int8Property; };
    template<> struct TCastFlagTraits<FInt16Property> { static constexpr EClassCastFlags Flag = EClassCastFlags::Int16Property; };
    template<> struct TCastFlagTraits<FInt64Property> { static constexpr EClassCastFlags Flag = EClassCastFlags::Int64Property; };
    template<> struct TCastFlagTraits<FUInt16Property> { static constexpr EClassCastFlags Flag = EClassCastFlags::UInt16Property; };
    template<> struct TCastFlagTraits<FUInt32Property> { static constexpr EClassCastFlags Flag = EClassCastFlags::UInt32Property; };
    template<> struct TCastFlagTraits<FUInt64Property> { static constexpr EClassCastFlags Flag = EClassCastFlags::UInt64Property; };
    template<> struct TCastFlagTraits<FFloatProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::FloatProperty; };
    template<> struct TCastFlagTraits<FDoubleProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::DoubleProperty; };
    template<> struct TCastFlagTraits<FStrProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::StrProperty; };
    template<> struct TCastFlagTraits<FNameProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::NameProperty; };
    template<> struct TCastFlagTraits<FTextProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::TextProperty; };
    template<> struct TCastFlagTraits<FObjectPropertyBase> { static constexpr EClassCastFlags Flag = EClassCastFlags::ObjectPropertyBase; };
    template<> struct TCastFlagTraits<FObjectProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::ObjectProperty; };
    template<> struct TCastFlagTraits<FClassProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::ClassProperty; };
    template<> struct TCastFlagTraits<FWeakObjectProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::WeakObjectProperty; };
    template<> struct TCastFlagTraits<FLazyObjectProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::LazyObjectProperty; };
    template<> struct TCastFlagTraits<FSoftObjectProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::SoftObjectProperty; };
    template<> struct TCastFlagTraits<FSoftClassProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::SoftClassProperty; };
    template<> struct TCastFlagTraits<FInterfaceProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::InterfaceProperty; };
    template<> struct TCastFlagTraits<FStructProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::StructProperty; };
    template<> struct TCastFlagTraits<FEnumProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::EnumProperty; };
    template<> struct TCastFlagTraits<FArrayProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::ArrayProperty; };
    template<> struct TCastFlagTraits<FMapProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::MapProperty; };
    template<> struct TCastFlagTraits<FSetProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::SetProperty; };
    template<> struct TCastFlagTraits<FOptionalProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::OptionalProperty; };
    template<> struct TCastFlagTraits<FDelegateProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::DelegateProperty; };
    template<> struct TCastFlagTraits<FMulticastDelegateProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::MulticastDelegateProperty; };
    template<> struct TCastFlagTraits<FFieldPathProperty> { static constexpr EClassCastFlags Flag = EClassCastFlags::FieldPathProperty; };

    inline bool HasFlag(const FField* Field, EClassCastFlags Flag)
    {
        if (!Field || !Field->ClassPrivate) return false;
        return (Field->ClassPrivate->CastFlags & static_cast<uint64>(Flag)) != 0;
    }

    template<typename T> bool     IsA(const FField* Field) { return HasFlag(Field, TCastFlagTraits<T>::Flag); }
    template<typename T> T* Cast(FField* Field) { return IsA<T>(Field) ? static_cast<T*>(Field) : nullptr; }
    template<typename T> const T* Cast(const FField* Field) { return IsA<T>(Field) ? static_cast<const T*>(Field) : nullptr; }
    template<typename T> T* CastChecked(FField* Field) { assert(IsA<T>(Field)); return static_cast<T*>(Field); }

    template<typename Fn>
    bool Visit(FField* Field, Fn&& Visitor)
    {
        if (!Field) return false;
        if (auto* p = Cast<FMapProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FSetProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FArrayProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FOptionalProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FClassProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FSoftClassProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FSoftObjectProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FWeakObjectProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FLazyObjectProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FObjectProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FObjectPropertyBase>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FStructProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FEnumProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FMulticastDelegateProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FDelegateProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FBoolProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FByteProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FFloatProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FDoubleProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FInt8Property>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FInt16Property>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FIntProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FInt64Property>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FUInt16Property>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FUInt32Property>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FUInt64Property>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FStrProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FNameProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FTextProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FInterfaceProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FFieldPathProperty>(Field)) { Visitor(p); return true; }
        if (auto* p = Cast<FProperty>(Field)) { Visitor(p); return true; }
        return false;
    }
} // namespace FieldCast